### PR TITLE
Make library installation and packaging friendly

### PR DESCRIPTION
**Pull request by palmskog**
We are currently using forks of the HTT library in two projects: [Toychain](https://github.com/certichain/toychain) and [Disel](https://github.com/DistributedComponents/disel), which leads to duplicated efforts in maintenance. 

This pull request is a first step towards a unified version of the library that incorporates all necessary features for our projects and makes it easy to install globally (either via OPAM or manually). I would be happy to maintain OPAM packages in the official Coq OPAM repository when everything is ready for that.

The key changes in this pull request are:
- flat namespacing for easy use of `Require`; everything is under `HTT` rather than `HTT.Core`
- `install` task in the top `Makefile`
- parallel-build-friendly `Makefile`
- added two files `spcm.v` and `coding.v`, used in both Toychain and Disel
- `opam` file that can be used locally or in Travis CI for building the project and its dependencies via pinning (and later submitted to the Coq OPAM repo)
- updated README with brief installation instructions

### CODE REVIEW

**Comment by germanD** [comment]
Hi @palmskog, I will ping @aleksnanevski  to get involved. A thing I am not sure about is the following, those "missing files" are not missing in HTT, they are files from FCSL. I understand you rather depend from one library than two, but I do not think it that the coding and PCM theories should be here... as they are not needed for HTT.

**Comment by palmskog** [comment]
@germanD OK I'll remove those files.

**Comment by aleksnanevski** [comment]
We will make an official release of the heaps library soon. Please give us a week or so.

**Comment by palmskog** [comment]
@aleksnanevski @germanD thanks, sounds great.

Do you have any suggestions for where you think the `spcm.v` and `coding.v` files would be best maintained? Right now, they are the only files (besides `array.v`) that build directly on HTT and are used in FCSL, Toychain, and Disel. Wouldn't it at least make sense to have them under `Examples`, like `array.v`?

**Comment by aleksnanevski** [comment]
Not sure. They are not used in FCSL anymore. You can keep them in your own build.

**Comment by palmskog** [comment]
@aleksnanevski @germanD any chance of merging this pull request and making a release on GitHub in the near future? Would help us out a lot with building/packaging in our projects.

**Comment by aleksnanevski** [comment]
We will make a release soon, completely different from what's here (i.e., unrelated to the pull request). But I have to clear some legal stuff with IMDEA ownership of the files. You'll be dully informed.

**Comment by anton-trunov** [comment]
Hi @palmskog! Sorry it took so long :( We just released https://github.com/imdea-software/fcsl-pcm (sorry it took so long). It's available on OPAM under coq-released. It's not fully compatible with htt, so if you decide to port your projects to fcsl-pcm, we can provide some assistance. Please let me know what you think. (CC @aleksnanevski)

**Pull request closed without merging**
