### PR TITLE
make coq-htt package depend on coq-htt-core

### PR DESCRIPTION
**Pull request by palmskog**
This approach could also be done with coq_makefile only, but much less conveniently (it would have to be like in the mathcomp repo with `make -C htt`/`make -C examples`).

### CODE REVIEW

**Comment by palmskog** [comment]
@aleksnanevski could you please approve the CI run here? There may have to be some fiddling.

**Comment by palmskog** [comment]
OK, this actually looks like it works (so feel free to merge). Note that `docker-action.yml` and `coq-htt.opam` and `examples/dune` can't be generated via templates anymore for the time being, but maintaining those manually should be straightforward.

**Comment by aleksnanevski** [comment]
So you're saying I can erase the whole templates-extra directory? What about meta.yml and dune-project?

**Comment by palmskog** [comment]
It's a good idea to keep `meta.yml` and use it to generated files like `README.md` and potentially `dune-project` as well. As for `templates-extra`, there doesn't look to be much point to keep the files there around.

There is no need to change any existing releases because of this - it will only affect (1) Git-based packages in `extra-dev` opam repo and (2) future releases. If you do a new release, e.g., `2.0.1`, then I can depend on this much easier in Disel than `2.0.0`.

**Comment by aleksnanevski** [comment]
Ok, I'll then make a new minor release 2.0.1, as you suggest.

**Pull request merged**
